import { RequestStatus } from "@/lib/types/request";

export const dataRequests = [
  {
    requestorName: "John Doe",
    itemRequested: "First Aid Kit",
    requestCreatedDate: new Date("2024-12-20"),
    lastEditedDate: new Date("2024-12-23"),
    status: RequestStatus.APPROVED,
  },
  {
    requestorName: "Alice Smith",
    itemRequested: "Bottled Water",
    requestCreatedDate: new Date("2024-12-18"),
    lastEditedDate: new Date("2024-12-18"),
    status: RequestStatus.PENDING,
  },
  {
    requestorName: "Bob Johnson",
    itemRequested: "Non-perishable Food",
    requestCreatedDate: new Date("2024-12-15"),
    lastEditedDate: new Date("2024-12-19"),
    status: RequestStatus.COMPLETED,
  },
  {
    requestorName: "Claire Wilson",
    itemRequested: "Flashlight",
    requestCreatedDate: new Date("2024-12-21"),
    lastEditedDate: new Date("2024-12-22"),
    status: RequestStatus.REJECTED,
  },
  {
    requestorName: "David Lee",
    itemRequested: "Blankets",
    requestCreatedDate: new Date("2024-12-16"),
    lastEditedDate: new Date("2024-12-17"),
    status: RequestStatus.APPROVED,
  },
  {
    requestorName: "Emma Davis",
    itemRequested: "Portable Radio",
    requestCreatedDate: new Date("2024-12-17"),
    lastEditedDate: new Date("2024-12-17"),
    status: RequestStatus.PENDING,
  },
  {
    requestorName: "Frank Taylor",
    itemRequested: "Backup Batteries",
    requestCreatedDate: new Date("2024-12-14"),
    lastEditedDate: new Date("2024-12-15"),
    status: RequestStatus.COMPLETED,
  },
  {
    requestorName: "Grace Hall",
    itemRequested: "Hygiene Kits",
    requestCreatedDate: new Date("2024-12-19"),
    lastEditedDate: new Date("2024-12-20"),
    status: RequestStatus.APPROVED,
  },
  {
    requestorName: "Helen Brown",
    itemRequested: "Prescription Medications",
    requestCreatedDate: new Date("2024-12-20"),
    lastEditedDate: null,
    status: RequestStatus.PENDING,
  },
  {
    requestorName: "Isaac Green",
    itemRequested: "Can Opener",
    requestCreatedDate: new Date("2024-12-13"),
    lastEditedDate: new Date("2024-12-14"),
    status: RequestStatus.REJECTED,
  },
  {
    requestorName: "Jennifer White",
    itemRequested: "Solar Phone Charger",
    requestCreatedDate: new Date("2024-12-21"),
    lastEditedDate: new Date("2024-12-22"),
    status: RequestStatus.COMPLETED,
  },
  {
    requestorName: "Kyle Harris",
    itemRequested: "Water Purification Tablets",
    requestCreatedDate: new Date("2024-12-18"),
    lastEditedDate: new Date("2024-12-20"),
    status: RequestStatus.APPROVED,
  },
  {
    requestorName: "Laura Martinez",
    itemRequested: "Emergency Shelter",
    requestCreatedDate: new Date("2024-12-19"),
    lastEditedDate: new Date("2024-12-19"),
    status: RequestStatus.PENDING,
  },
  {
    requestorName: "Michael Clark",
    itemRequested: "Fire Extinguisher",
    requestCreatedDate: new Date("2024-12-16"),
    lastEditedDate: new Date("2024-12-17"),
    status: RequestStatus.REJECTED,
  },
  {
    requestorName: "Nina Adams",
    itemRequested: "Duct Tape",
    requestCreatedDate: new Date("2024-12-15"),
    lastEditedDate: new Date("2024-12-16"),
    status: RequestStatus.PENDING,
  },
];
